#!/bin/bash

cp .* /home/stoye/

cp pacman.conf /etc/pacman.conf

cp welcome /usr/bin/welcome

YAJL=$(pacman -Qs yajl)
if [ -n "$YAJL" ]
    then echo "yajl installed"
    else pacman -S --noconfirm yajl
fi

WGET=$(pacman -Qs wget)
if [ -n "$WGET" ]
    then echo "wget installed"
    else pacman -S --noconfirm wget
fi

PACKAGE_QUERY=$(pacman -Qs package-query)
if [ -n "$PACKAGE_QUERY" ]
    then echo "package-query installed"
    else wget https://aur.archlinux.org/packages/pa/package-query/package-query.tar.gz -O /home/stoye/package-query.tar.gz && tar -xf /home/stoye/package-query.tar.gz && cd /home/stoye/package-query && makepkg --asroot && pacman -U *.xz
fi

YAOURT=$(pacman -Qs yaourt)
if [ -n "$YAOURT" ]
    then echo "yaourt installed"
    else wget https://aur.archlinux.org/packages/ya/yaourt/yaourt.tar.gz -O /home/stoye/yaourt.tar.gz && tar -xf /home/stoye/yaourt.tar.gz && cd /home/stoye/yaourt && makepkg --asroot && pacman -U *.xz
fi

AURA=$(pacman -Qs aura)
if [ -n "$AURA" ]
    then echo "aura installed"
    else yaourt -S --noconfirm aura
fi

FIGLET=$(pacman -Qs figlet)
if [ -n "$FIGLET" ]
    then echo "figlet installed"
    else pacman -S --noconfirm figlet
fi

COWSAY=$(pacman -Qs cowsay)
if [ -n "$COWSAY" ]
    then echo "cowsay installed"
    else pacman -S --noconfirm cowsay
fi

FORTUNE=$(pacman -Qs fortune-mod)
if [ -n "$FORTUNE" ]
    then echo "fortune-mod installed"
    else pacman -S --noconfirm fortune-mod
fi

GIT=$(pacman -Qs git)
if [ -n "$GIT" ]
    then echo "git installed"
    else pacman -S --noconfirm git
fi

if [ ! -d "/home/stoye/102fortune" ]
    then git clone https://github.com/stoye/102fortune.git /home/stoye/102fortune
fi


cd /home/stoye/102fortune && ./install
