#!/bin/bash

cp /home/stoye/dotfiles/.* /home/stoye/

cp pacman.conf /etc/pacman.conf

cp welcome /usr/bin/welcome

WGET=$(pacman -Qs wget)
if [ -n "$WGET" ]
    then echo "wget installed"
    else pacman -S --noconfirm wget
fi

FIGLET=$(pacman -Qs figlet)
if [ -n "$FIGLET" ]
    then echo "figlet installed"
    else pacman -S --noconfirm figlet
fi

COWSAY=$(pacman -Qs cowsay)
if [ -n "$COWSAY" ]
    then echo "cowsay installed"
    else pacman -S --noconfirm cowsay
fi

FORTUNE=$(pacman -Qs fortune-mod)
if [ -n "$FORTUNE" ]
    then echo "fortune-mod installed"
    else pacman -S --noconfirm fortune-mod
fi

GIT=$(pacman -Qs git)
if [ -n "$GIT" ]
    then echo "git installed"
    else pacman -S --noconfirm git
fi

if [ ! -d "/home/stoye/102fortune" ]
    then git clone https://github.com/stoye/102fortune.git /home/stoye/102fortune
fi

cd /home/stoye/102fortune && ./install

if [ ! -d "/home/stoye/.oh-my-zsh" ]
then git clone https://github.com/stoye/oh-my-zsh.git /home/stoye/.oh-my-zsh
fi
